// Default initial seed data for offline / preview mode
export const initialCategories = [
  {
    id: 1,
    name: "Laminated Doors",
    slug: "laminated-doors",
    image: "/images/products/product-1.jpg",
    image_url: "/images/products/product-1.jpg",
    description: "High-pressure decorative laminate surface with high scratch and water resistance.",
  },
  {
    id: 2,
    name: "Membrane Doors",
    slug: "membrane-doors",
    image: "/images/products/product-2.jpg",
    image_url: "/images/products/product-2.jpg",
    description: "Precision CNC routed doors encased in seamless PVC foil.",
  },
  {
    id: 3,
    name: "Flush Doors",
    slug: "flush-doors",
    image: "/images/products/product-3.jpg",
    image_url: "/images/products/product-3.jpg",
    description: "Solid engineered timber core flush doors with superior acoustic insulation.",
  },
  {
    id: 4,
    name: "Designer Doors",
    slug: "designer-doors",
    image: "/images/products/product-4.jpg",
    image_url: "/images/products/product-4.jpg",
    description: "Artisanal entrance doors featuring custom geometric textures and luxury inlays.",
  },
  {
    id: 5,
    name: "Wooden Doors",
    slug: "wooden-doors",
    image: "/images/products/product-1.jpg",
    image_url: "/images/products/product-1.jpg",
    description: "Natural hardwood seasoned doors crafted for timeless durability.",
  },
  {
    id: 6,
    name: "Amez Door",
    slug: "amez-door",
    image: "/images/products/product-2.jpg",
    image_url: "/images/products/product-2.jpg",
    description: "Modern architectural collection with European styling.",
  },
];

export const initialProducts = [
  {
    id: 1,
    name: "Royal Teak Laminated Door",
    slug: "royal-teak-laminated-door",
    category: "Laminated Doors",
    categorySlug: "laminated-doors",
    category_slug: "laminated-doors",
    category_id: 1,
    image: "/images/products/product-1.jpg",
    image_url: "/images/products/product-1.jpg",
    is_featured: true,
    description: "Engineered with heavy-duty kiln-dried timber and encased in high-density European laminate sheets.",
    features: ["Scratch & Impact Resistant", "Water Repellent Finish", "Borer & Termite Proof", "10-Year Warranty"],
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 2,
    name: "Modern Geometric Membrane Door",
    slug: "modern-geometric-membrane-door",
    category: "Membrane Doors",
    categorySlug: "membrane-doors",
    category_slug: "membrane-doors",
    category_id: 2,
    image: "/images/products/product-2.jpg",
    image_url: "/images/products/product-2.jpg",
    is_featured: true,
    description: "Crafted on high-density fiberboard with computer-guided CNC grooves and vacuum membrane pressing.",
    features: ["Zero Joint Seamless Foil", "High Dimensional Stability", "Low Maintenance", "Modern Architectural CNC Pattern"],
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 3,
    name: "Architectural Solid Flush Door",
    slug: "architectural-solid-flush-door",
    category: "Flush Doors",
    categorySlug: "flush-doors",
    category_slug: "flush-doors",
    category_id: 3,
    image: "/images/products/product-3.jpg",
    image_url: "/images/products/product-3.jpg",
    is_featured: true,
    description: "Solid hardwood battens bounded under high temperature and pressure with phenolic resin.",
    features: ["IS:2202 Certified Quality", "Solid Pinewood Core", "Acoustic Noise Reduction", "High Screw Holding Capacity"],
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 4,
    name: "Signature Carved Designer Door",
    slug: "signature-carved-designer-door",
    category: "Designer Doors",
    categorySlug: "designer-doors",
    category_slug: "designer-doors",
    category_id: 4,
    image: "/images/products/product-4.jpg",
    image_url: "/images/products/product-4.jpg",
    is_featured: true,
    description: "Statement entrance door created for luxury residential projects with multi-layer carved elements.",
    features: ["Handcrafted Textures", "UV-Resistant Protective Lacquer", "Heavy Hardware Compatible", "Weather Resistant Seal"],
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 5,
    name: "Classic Oak Wood Door",
    slug: "classic-oak-wood-door",
    category: "Wooden Doors",
    categorySlug: "wooden-doors",
    category_slug: "wooden-doors",
    category_id: 5,
    image: "/images/products/product-1.jpg",
    image_url: "/images/products/product-1.jpg",
    is_featured: false,
    description: "Natural hardwood construction showcasing rich organic grain patterns and deep satin luster.",
    features: ["Natural Timber Grains", "Thermal Insulation", "Kiln-Seasoned Wood", "Eco-Friendly Polish"],
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 6,
    name: "Amez Prime Minimal Door",
    slug: "amez-prime-minimal-door",
    category: "Amez Door",
    categorySlug: "amez-door",
    category_slug: "amez-door",
    category_id: 6,
    image: "/images/products/product-2.jpg",
    image_url: "/images/products/product-2.jpg",
    is_featured: false,
    description: "European minimalist interior door designed to complement modern contemporary spaces.",
    features: ["Concealed Hinge Ready", "Matte Texture", "Moisture Resistant", "Sound Dampening Core"],
    created_at: new Date().toISOString(),
  },
];
