import React, { useState } from 'react';
import { supabase } from '../../services/supabaseClient';
import { Plus, Edit3, Trash2, FolderPlus, Loader2, Save, X, Image as ImageIcon } from 'lucide-react';

export default function CategoriesTab({ categories, onCategoryAdded, onDeleteCategory }) {
  const [editingId, setEditingId] = useState(null);
  const [submitting, setSubmitting] = useState(false);

  // Form State
  const [formData, setFormData] = useState({
    name: '',
    slug: '',
    image: '',
  });

  // Automatically generate slug when category name changes
  const handleNameChange = (name) => {
    const slug = name
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-');

    setFormData((prev) => ({ ...prev, name, slug }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!formData.name) return;
    setSubmitting(true);

    try {
      if (editingId) {
        // Edit Existing Category
        const { error } = await supabase
          .from('categories')
          .update({
            name: formData.name,
            slug: formData.slug,
            image: formData.image,
          })
          .eq('id', editingId);

        if (error) throw error;
      } else {
        // Add New Category (ID is auto-generated by Supabase)
        const { error } = await supabase
          .from('categories')
          .insert([{
            name: formData.name,
            slug: formData.slug,
            image: formData.image,
          }]);

        if (error) throw error;
      }

      // Reset form and refresh parent data
      handleReset();
      if (onCategoryAdded) onCategoryAdded();
    } catch (err) {
      alert('Error saving category: ' + err.message);
    } finally {
      setSubmitting(false);
    }
  };

  const handleEditClick = (cat) => {
    setEditingId(cat.id);
    setFormData({
      name: cat.name,
      slug: cat.slug,
      image: cat.image || '',
    });
  };

  const handleReset = () => {
    setEditingId(null);
    setFormData({ name: '', slug: '', image: '' });
  };

  return (
    <div className="space-y-8">
      
      {/* Inline Form Card */}
      <div className="bg-zinc-900 border border-zinc-800 p-6 rounded-2xl shadow-xl">
        <div className="flex items-center gap-3 mb-6">
          <div className="bg-red-600/10 text-red-500 p-2.5 rounded-xl border border-red-500/20">
            <FolderPlus size={22} />
          </div>
          <div>
            <h2 className="text-lg font-black text-white uppercase tracking-wide">
              {editingId ? 'Edit Category' : 'Add New Category'}
            </h2>
            <p className="text-xs text-zinc-400">
              Create door collections (e.g. AMEZ DOOR, ICON GROOVING)
            </p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            
            {/* Category Name */}
            <div>
              <label className="block text-xs font-bold text-zinc-400 uppercase mb-1">
                Category Name
              </label>
              <input
                type="text"
                required
                placeholder="e.g. AMEZ DOOR"
                value={formData.name}
                onChange={(e) => handleNameChange(e.target.value)}
                className="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-red-600 transition"
              />
            </div>

            {/* Auto Generated Slug */}
            <div>
              <label className="block text-xs font-bold text-zinc-400 uppercase mb-1">
                Slug (Auto Generated)
              </label>
              <input
                type="text"
                required
                readOnly
                placeholder="amez-door"
                value={formData.slug}
                className="w-full bg-zinc-950/60 border border-zinc-800/80 rounded-xl px-4 py-2.5 text-sm text-red-400 font-mono"
              />
            </div>

            {/* Image URL */}
            <div>
              <label className="block text-xs font-bold text-zinc-400 uppercase mb-1">
                Image URL
              </label>
              <input
                type="url"
                placeholder="https://images.unsplash.com/..."
                value={formData.image}
                onChange={(e) => setFormData({ ...formData, image: e.target.value })}
                className="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-red-600 transition"
              />
            </div>

          </div>

          {/* Form Action Buttons */}
          <div className="flex items-center justify-end gap-3 pt-3 border-t border-zinc-800">
            {editingId && (
              <button
                type="button"
                onClick={handleReset}
                className="px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 font-bold text-xs rounded-xl transition flex items-center gap-2 cursor-pointer"
              >
                <X size={16} /> Cancel
              </button>
            )}

            <button
              type="submit"
              disabled={submitting}
              className="px-6 py-2.5 bg-red-600 hover:bg-red-700 disabled:bg-zinc-800 text-white font-bold text-xs rounded-xl transition shadow-lg flex items-center gap-2 cursor-pointer"
            >
              {submitting ? (
                <Loader2 size={16} className="animate-spin" />
              ) : editingId ? (
                <Save size={16} />
              ) : (
                <Plus size={16} />
              )}
              <span>{editingId ? 'Update Category' : 'Save Category'}</span>
            </button>
          </div>
        </form>
      </div>

      {/* Categories Grid List */}
      <div>
        <h3 className="text-xs font-bold uppercase tracking-wider text-zinc-400 mb-4">
          All Categories ({categories ? categories.length : 0})
        </h3>

        {!categories || categories.length === 0 ? (
          <div className="bg-zinc-900/50 border border-zinc-800 rounded-2xl p-8 text-center text-zinc-500 text-sm">
            No categories created yet. Use the form above to add one.
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {categories.map((cat) => (
              <div
                key={cat.id}
                className={`bg-zinc-900 border rounded-2xl p-4 flex items-center gap-4 transition group ${
                  editingId === cat.id ? 'border-red-600 bg-red-950/10' : 'border-zinc-800 hover:border-zinc-700'
                }`}
              >
                {/* Thumbnail */}
                <div className="w-16 h-16 rounded-xl bg-zinc-950 border border-zinc-800 overflow-hidden flex-shrink-0 flex items-center justify-center">
                  {cat.image ? (
                    <img
                      src={cat.image}
                      alt={cat.name}
                      className="w-full h-full object-cover group-hover:scale-110 transition duration-300"
                      onError={(e) => {
                        e.target.style.display = 'none';
                      }}
                    />
                  ) : (
                    <ImageIcon size={20} className="text-zinc-600" />
                  )}
                </div>

                {/* Details */}
                <div className="flex-1 min-w-0">
                  <h4 className="font-extrabold text-white text-sm truncate">{cat.name}</h4>
                  <span className="text-[10px] text-red-400 font-mono bg-red-950/40 border border-red-500/20 px-2 py-0.5 rounded-md inline-block mt-1">
                    {cat.slug}
                  </span>
                </div>

                {/* Action Buttons */}
                <div className="flex flex-col gap-1">
                  <button
                    onClick={() => handleEditClick(cat)}
                    className="p-1.5 text-zinc-400 hover:text-white hover:bg-zinc-800 rounded-lg transition cursor-pointer"
                    title="Edit Category"
                  >
                    <Edit3 size={15} />
                  </button>
                  <button
                    onClick={() => onDeleteCategory(cat.id, cat.name)}
                    className="p-1.5 text-zinc-400 hover:text-red-500 hover:bg-zinc-800 rounded-lg transition cursor-pointer"
                    title="Delete Category"
                  >
                    <Trash2 size={15} />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

    </div>
  );
}